
on: push
jobs:
  test:
    runs-on : ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: ros2 build
        run: |
          mkdir -p /root/ros2_ws/src/pkg_kadai 
          rsync -av ./ /root/ros2_ws/src/pkg_kadai/
          cd /root/ros2_ws
          colcon build
          source install/setup.bash

          echo "TestTestesttetst" | timeout 5s ros2 run pkg_kadai player1 || [ $? -eq 124 ]
          echo "TeststeststeTest" | timeout 5s ros2 run pkg_kadai player2 || [ $? -eq 124 ]
      - name: test
        run: python3 test/test.py


