
on: push
jobs:
  test:
    runs-on : ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: ros2 build
        run: |
          mkdir -p /root/ros2_ws/src/pkg_kadai 
          rsync -av ./ /root/ros2_ws/src/pkg_kadai/
          cd /root/ros2_ws
          colcon build
          source install/setup.bash
          
      - name: test
        run: |
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          cd /root/ros2_ws/src/pkg_kadai/test
          python3 test/test.py



