name: setup
on: push
jobs:
  test:
    runs-on : ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    shell: bash
    steps:
      - uses: actions/checkout@v2

      - run: | 
          rsync -av ./ /root/ros2_ws/src/pkg_kadai/
          cd /root/ros2_ws
          colcon build
          source /opt/ros/$ROS_DISTRO/setup.bash
          source install/setup.bash

