
on: push
jobs:
  test:
    runs-on : ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - name: ros2 build
        run: |
          mkdir -p /root/ros2_ws/src/pkg_kadai
          mkdir -p /root/ros2_ws/src/pkg_kadai2
          mkdir -p /root/ros2_ws/src/pkg_kadai3
          rsync -av ./ /root/ros2_ws/src/pkg_kadai/
          rsync -av ./ /root/ros2_ws/src/pkg_kadai2/ 
          rsync -av ./ /root/ros2_ws/src/pkg_kadai3/
          sed "s@<name>pkg_kadai@<name>pkg_kadai2@g" /root/ros2_ws/src/pkg_kadai2/package.xml
          sed "s@<name>pkg_kadai@<name>pkg_kadai3@g" /root/ros2_ws/src/pkg_kadai3/package.xml
          sed "s@lib/pkg_kadai@lib/pkg_kadai2@g" /root/ros2_ws/src/pkg_kadai/setup.cfg
          sed "s@lib/pkg_kadai@lib/pkg_kadai3@g" /root/ros2_ws/src/pkg_kadai/setup.cfg
          sed "s@package_name = 'pkg_kadai'@package_name = 'pkg_kadai2'@g" /root/ros2_ws/src/pkg_kadai/setup.py
          sed "s@package_name = 'pkg_kadai'@package_name = 'pkg_kadai3'@g" /root/ros2_ws/src/pkg_kadai/setup.py
          cd /root/ros2_ws
          colcon build
          source install/setup.bash

          
      - name: test
        run: |
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          cd /root/ros2_ws/src/pkg_kadai/test
          bash -xv ./test.bash



